export const products = [
  {
    id: '940fd98b-6b47-4b3c-b777-76e0fa0327e2',
    Name: 'Unbranded Steel Table',
    Price: 38.0,
    Description:
      "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
    Category: 'Clothing',
    Type: 'Refined',
    Image: 'http://placeimg.com/640/480/sports',
    Manufacturer: 'Tesla',
    Seller: "O'Keefe, Dach and Schuster",
    Quantity: 21126,
    Tax: 0.97,
  },
  {
    id: '0fe2cd06-9b91-4e76-893a-3af56bbea55d',
    Name: 'Intelligent Soft Bacon',
    Price: 209.0,
    Description:
      'Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals',
    Category: 'Movies',
    Type: 'Handcrafted',
    Image: 'http://placeimg.com/640/480/abstract',
    Manufacturer: 'Fiat',
    Seller: 'Denesik and Sons',
    Quantity: 83951,
    Tax: 0.81,
  },
  {
    id: 'dd4923bb-ae35-49b0-a978-c03c00058a8b',
    Name: 'Handcrafted Metal Computer',
    Price: 953.0,
    Description:
      'New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart',
    Category: 'Industrial',
    Type: 'Awesome',
    Image: 'http://placeimg.com/640/480/nature',
    Manufacturer: 'Audi',
    Seller: 'Crooks - Crona',
    Quantity: 4651,
    Tax: 0.32,
  },
  {
    id: '50602915-f7f2-41b2-90bc-b76b7d6db063',
    Name: 'Handcrafted Plastic Cheese',
    Price: 163.0,
    Description:
      'Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals',
    Category: 'Beauty',
    Type: 'Awesome',
    Image: 'http://placeimg.com/640/480/city',
    Manufacturer: 'Ford',
    Seller: 'Pacocha and Sons',
    Quantity: 18497,
    Tax: 0.45,
  },
  {
    id: 'b1b3deca-7c7b-428e-adf3-6a95942d375e',
    Name: 'Practical Rubber Chair',
    Price: 407.0,
    Description:
      'New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016',
    Category: 'Toys',
    Type: 'Handmade',
    Image: 'http://placeimg.com/640/480/nightlife',
    Manufacturer: 'Chevrolet',
    Seller: "D'Amore, Bednar and Waelchi",
    Quantity: 81735,
    Tax: 0.11,
  },
  {
    id: '2f6d6b20-e972-4757-8c05-39eb25536051',
    Name: 'Refined Metal Chair',
    Price: 867.0,
    Description: 'The Football Is Good For Training And Recreational Purposes',
    Category: 'Computers',
    Type: 'Awesome',
    Image: 'http://placeimg.com/640/480/sports',
    Manufacturer: 'Land Rover',
    Seller: 'Russel, Haag and Torphy',
    Quantity: 66836,
    Tax: 0.15,
  },
  {
    id: '3cbbd22d-accb-4e48-a695-35ccdd6e2fa3',
    Name: 'Unbranded Concrete Tuna',
    Price: 113.0,
    Description: 'The Football Is Good For Training And Recreational Purposes',
    Category: 'Music',
    Type: 'Handmade',
    Image: 'http://placeimg.com/640/480/transport',
    Manufacturer: 'Jaguar',
    Seller: 'Bogisich - Fisher',
    Quantity: 22988,
    Tax: 0.78,
  },
  {
    id: '9ad50724-8d4b-40f2-8033-99f6a3e9fb3d',
    Name: 'Generic Cotton Bike',
    Price: 510.0,
    Description:
      'New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart',
    Category: 'Automotive',
    Type: 'Handmade',
    Image: 'http://placeimg.com/640/480/nature',
    Manufacturer: 'Bugatti',
    Seller: 'Kuphal, Kling and Labadie',
    Quantity: 93613,
    Tax: 0.16,
  },
  {
    id: 'f48288ad-7f5f-4e2a-9d16-d978c720c3e1',
    Name: 'Awesome Soft Keyboard',
    Price: 596.0,
    Description:
      'The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients',
    Category: 'Shoes',
    Type: 'Intelligent',
    Image: 'http://placeimg.com/640/480/people',
    Manufacturer: 'Dodge',
    Seller: 'Metz, Kulas and Zulauf',
    Quantity: 87936,
    Tax: 0.68,
  },
  {
    id: 'ba45fd8d-ab67-49b2-91b2-a1af82e68107',
    Name: 'Handmade Frozen Mouse',
    Price: 644.0,
    Description:
      'The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J',
    Category: 'Outdoors',
    Type: 'Gorgeous',
    Image: 'http://placeimg.com/640/480/abstract',
    Manufacturer: 'Bentley',
    Seller: 'Ebert - Gleichner',
    Quantity: 25962,
    Tax: 0.64,
  },
  {
    id: '10409826-4ec5-4f9f-bd66-5501d2ad4218',
    Name: 'Rustic Steel Salad',
    Price: 239.0,
    Description:
      "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
    Category: 'Beauty',
    Type: 'Intelligent',
    Image: 'http://placeimg.com/640/480/technics',
    Manufacturer: 'Cadillac',
    Seller: 'Goodwin Inc',
    Quantity: 1220,
    Tax: 0.24,
  },
  {
    id: '4f577f7e-3631-4825-9a23-08cc296cc5fb',
    Name: 'Generic Plastic Table',
    Price: 51.0,
    Description:
      'Carbonite web goalkeeper gloves are ergonomically designed to give easy fit',
    Category: 'Toys',
    Type: 'Refined',
    Image: 'http://placeimg.com/640/480/nature',
    Manufacturer: 'BMW',
    Seller: 'Torphy, Mann and Parker',
    Quantity: 51882,
    Tax: 1,
  },
  {
    id: '0c2dccd6-ea2e-4dc3-a2ee-1d68f38274cd',
    Name: 'Unbranded Soft Tuna',
    Price: 138.0,
    Description:
      'The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J',
    Category: 'Music',
    Type: 'Gorgeous',
    Image: 'http://placeimg.com/640/480/cats',
    Manufacturer: 'Audi',
    Seller: 'Stamm - Wilderman',
    Quantity: 21162,
    Tax: 0.54,
  },
  {
    id: '474e3d96-e01f-44d8-844b-f6c2cd84957a',
    Name: 'Unbranded Soft Car',
    Price: 700.0,
    Description:
      'New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart',
    Category: 'Music',
    Type: 'Awesome',
    Image: 'http://placeimg.com/640/480/fashion',
    Manufacturer: 'Aston Martin',
    Seller: 'Kuhlman, Will and Reichel',
    Quantity: 47705,
    Tax: 0.77,
  },
  {
    id: 'cb4975dd-b950-4c7a-8b13-8683805d6bea',
    Name: 'Fantastic Rubber Chair',
    Price: 211.0,
    Description:
      'New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart',
    Category: 'Automotive',
    Type: 'Small',
    Image: 'http://placeimg.com/640/480/abstract',
    Manufacturer: 'Ferrari',
    Seller: 'Bradtke - Renner',
    Quantity: 20177,
    Tax: 0.86,
  },
  {
    id: 'db0f1c84-36b3-496f-a6b4-b360a6cf2900',
    Name: 'Awesome Cotton Mouse',
    Price: 608.0,
    Description:
      'The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality',
    Category: 'Outdoors',
    Type: 'Gorgeous',
    Image: 'http://placeimg.com/640/480/fashion',
    Manufacturer: 'Dodge',
    Seller: 'Lowe, Hermiston and Bradtke',
    Quantity: 33245,
    Tax: 0.46,
  },
  {
    id: '45004dd9-1c14-41b5-9ab1-6bbfa1d52922',
    Name: 'Licensed Plastic Tuna',
    Price: 704.0,
    Description:
      'The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive',
    Category: 'Games',
    Type: 'Rustic',
    Image: 'http://placeimg.com/640/480/cats',
    Manufacturer: 'Nissan',
    Seller: 'Streich, Keebler and Wilderman',
    Quantity: 17773,
    Tax: 1,
  },
  {
    id: '09ece494-d526-4785-ace4-44e6b54ac07a',
    Name: 'Small Soft Shirt',
    Price: 323.0,
    Description:
      'New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart',
    Category: 'Baby',
    Type: 'Handmade',
    Image: 'http://placeimg.com/640/480/city',
    Manufacturer: 'Tesla',
    Seller: 'Farrell - Lemke',
    Quantity: 35297,
    Tax: 0.98,
  },
  {
    id: 'fbe2fe10-a34f-4a7d-81f6-b77665902d17',
    Name: 'Handmade Concrete Chicken',
    Price: 498.0,
    Description:
      "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
    Category: 'Shoes',
    Type: 'Practical',
    Image: 'http://placeimg.com/640/480/transport',
    Manufacturer: 'Fiat',
    Seller: 'Parker - Effertz',
    Quantity: 92572,
    Tax: 0.43,
  },
  {
    id: '6a812340-0cc6-4b38-9279-494b1fd4bbb1',
    Name: 'Intelligent Soft Mouse',
    Price: 161.0,
    Description:
      'The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive',
    Category: 'Shoes',
    Type: 'Practical',
    Image: 'http://placeimg.com/640/480/food',
    Manufacturer: 'Rolls Royce',
    Seller: 'Strosin - Mraz',
    Quantity: 31675,
    Tax: 0.86,
  },
];
